<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE beans [
        <!ELEMENT beans (bean)*>
        <!ATTLIST beans
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xmlns:aop CDATA #REQUIRED
                xmlns:context CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                class CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT property (ref|value|list)*>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #IMPLIED
                value CDATA #IMPLIED>
        <!ELEMENT ref (#PCDATA)>
        <!ATTLIST ref
                bean CDATA #REQUIRED>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT list (ref)*>
        ]>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aop="http://www.springframework.org/schema/aop"
	xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd
       http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.1.xsd
	   http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.1.xsd">
	<bean id="taskService" class="com.bfd.ca.service.TaskService" />
	<bean id="oneMinTask"
		class="org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean">
		<property name="targetObject">
			<ref bean="taskService" />
		</property>
		<property name="targetMethod">
			<value>oneMinTask</value>
		</property>
		<property name="concurrent">
			<value>false</value>
		</property>
	</bean>
	<!-- 每天执行 -->
	<bean id="oneMinTriggerBean" class="org.springframework.scheduling.quartz.CronTriggerBean">
		<property name="jobDetail" ref="oneMinTask"></property>
		<property name="startDelay" value="5000" />
		<property name="cronExpression" value="0 0/1 * * * ?" />
	</bean>
	<bean id="SpringJobSchedulerFactoryBean"
		class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
		<property name="triggers">
			<list>
				<ref bean="oneMinTriggerBean" />
			</list>
		</property>
	</bean>

</beans>